//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazybones.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Job
    {
        public string Title { get; set; }
        public string Description { get; set; }
        [Display(Name = "Starts")]
        public Nullable<System.DateTime> Start_Time_Date { get; set; }
        [Display(Name = "Expires")]
        public Nullable<System.DateTime> Expirey_Time_Date { get; set; }
        public string Category { get; set; }
        [Display(Name = "Flat rate pay")]
        public Nullable<decimal> Pay { get; set; }
        [Display(Name = "Or best bid")]
        public bool Best_Bid { get; set; }
        public string Picture_Location { get; set; }
        [Display(Name = "Date completed")]
        public Nullable<System.DateTime> Date_Completed { get; set; }
        public string Poster_Name { get; set; }
        public string Getter_Name { get; set; }
        public string Status { get; set; }
        public int ID { get; set; }
        [Display(Name = "Payment status")]
        public string Payment_Status { get; set; }
        [Display(Name = "Call")]
        public bool Contact_By_Phone { get; set; }
        [Display(Name = "Email")]
        public bool Contact_By_Email { get; set; }
        [Display(Name = "Text")]
        public bool Contact_By_Text { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string State { get; set; }
        public string Getter { get; set; }
        public string Poster { get; set; }
        [Display(Name = "Current bid amount")]
        public Nullable<decimal> Bid_Amount { get; set; }
        [Display(Name = "Gig location same as home?")]
        public bool Same_as_Home { get; set; }
    }
}
