//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Lazybones.Models
{

    public partial class User
    {
        public string Email { get; set; }
        public string Password { get; set; }
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        [Display(Name = "Mobile Phone")]
        public string Mobile_Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        [Display(Name = "Preferred Contact Method")]
        public string Preferred_Contact_Method { get; set; }
        [Display(Name = "Gig Poster")]
        public bool Gig_Poster { get; set; }
        [Display(Name = "Go-Getter")]
        public bool Go_Getter { get; set; }
    }
}
